### ISSUE TITLE
Is it possible to safely unload kext and kill script?

### ISSUE THREAD

**Issue by kibin** [pignoniG/Load_Tunderbolt#1]
Tried it through automator (with `kextunload` command) and it was a success... and then macos crashed. So is there a way to unload kext on the fly?

**Comment by Joebeazelman** [comment]
Hmmm? Without knowing the details of the software you're using.  I suspect there's a process using the Kext and by unloading it, it's causing the machine to freak out. 

On another related topic, what's the condition of your battery?  Have you performed an extensive diagnostic test of your battery?  If there's reported issue, does your battery exhibit an inability to hold a charge for very long? 

I have a nagging suspicion that the problem may be related to power management unit or the battery itself.

**Comment by kibin** [comment]
The motivation for this wasn’t battery issues, I was just curious if I could somehow load kext when it’s needed and then unload it if it’s not, but yeah, the machine freaked out.

After a while I gave up on moving/unloading kext completely (moreover as far as I know in catalina they’ve blocked the possibility to move them from the default directory), played a bit with a script (it now occupies somewhere ~ 3-5% of a CPU) and added it to startup items. Macbook sometimes randomly shuts itself, but it’s not so often.

So I think the problem is not relevant now, closing.
